# Generated by Django 6.0 on 2025-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'American'), ('BRL', 'Brazilian'), ('UK', 'British')], max_length=50, null=True, verbose_name='Nacionalidade')),
            ],
        ),
    ]
